# Generated by Django 6.0.2 on 2026-03-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_feedback_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
